//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3Eksamen_PET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Report Report { get; set; }
    }
}
